### ISSUE TITLE
support cleaning up a list of resources

### ISSUE THREAD

**Issue by amirschw** [itaysk/kubectl-neat#11]
This is a **feature** request.

While cleaning up a single resource is great, it could also be nice to clean up a whole list of resources.

For example, I would like to do `kubectl neat pod -n mynamespace -oyaml` in order to get all the uncluttered pods in my namespace.

I can make the PR if you find this useful :)

**Comment by itaysk** [comment]
Hi @amirschw! Yes this is a great suggestion, feel free to submit a PR.

**Comment by amirschw** [comment]
Hey @itaysk! :) Will do

**Comment by itaysk** [comment]
this is now released in v1.2.0
