### ISSUE TITLE
eliminate redundant CI runs

### ISSUE THREAD

**Issue by itaysk** [itaysk/kubectl-neat#20]
https://github.com/itaysk/kubectl-neat/pull/13 added basic CI but I noticed it's building twice on a common use case: once for push and again for PR event. the fix is probably something with adding branch filtering to the triggers.

**Comment by AsterYujano** [comment]
Hello, 
I am starting to work on that issue :)
Will submit a PR once it is done

**Comment by itaysk** [comment]
Thank you!

**Comment by karancode** [comment]
I will work on this to fix it.

**Comment by itaysk** [comment]
thank you @karancode
