### ISSUE TITLE
Fully support List type

### ISSUE THREAD

**Issue by howardjohn** [itaysk/kubectl-neat#31]
This is useful to do things like `kubectl get pods -oyaml | kubectl neat`. Currently it seems like it does some work, but there are a few fields like `managedFields` that stick around. Using v1.1.1

**Comment by itaysk** [comment]
thanks for taking the time to report! this issue is tracked in https://github.com/itaysk/kubectl-neat/issues/11 and will be resolved soon. I'm closing this issue as a duplicate, feel free to reopen if needed.

**Comment by itaysk** [comment]
this is now released in v1.2.0
