### ISSUE TITLE
Neat is printing output to stderr

### ISSUE THREAD

**Issue by eyalzek** [itaysk/kubectl-neat#40]
Not sure if it's intended or not, I assume it was introduced in this commit:
https://github.com/itaysk/kubectl-neat/commit/297ddffeab0664d8615b0586ddffaf3b35ba661f

My use case for neat was something like: `kubectl get po foo -oyaml | kubectl neat > foo.yaml` which I noticed stopped working on the latest version. Redirecting stderr to the file will of course work: `kubectl get po foo -oyaml | kubectl neat 2> foo.yaml`, but this is not conforming to the usual `kubectl get` behavior which is to print to stdout.

**Comment by itaysk** [comment]
@eyalzek I'm sorry for this horrible regression! will fix that today as soon as possible

**Comment by itaysk** [comment]
This issue was closed automatically since the PR was merged, however I will release this version only tomorrow
