### ISSUE TITLE
Using neat on windows 64-bit platform 

### ISSUE THREAD

**Issue by djkormo** [itaysk/kubectl-neat#51]
k krew install neat
Updated the local copy of plugin index.
Installing plugin: neat
W1217 13:46:29.914981   16380 install.go:164] failed to install plugin "neat": plugin "neat" does not offer installation for this platform
F1217 13:46:29.952985   16380 root.go:79] failed to install some plugins: [neat]: plugin "neat" does not offer installation for this platform
exit status 255

**Comment by itaysk** [comment]
@djkormo yes, we don't have windows release yet, see https://github.com/itaysk/kubectl-neat/issues/6
It should be very easy task to pick up
