### ISSUE TITLE
incorporate kubectl-neat-diff into functionality and installation

### ISSUE THREAD

**Issue by mleklund** [itaysk/kubectl-neat#65]
@sh0rez has [created a cool tool](https://github.com/sh0rez/kubectl-neat-diff) for diff'ing and since it is built off of kubectl-neat, I thought I might suggest you coming together and creating one toolset similar kubectx/kubens.

**Comment by itaysk** [comment]
thanks for opening an issue! personally I think like the "unix philosophy" of composable tools. So for example this would work well: `diff <(kubectl-neat -f one.yaml) <(kubectl-neat -f two.yaml)` as suggested in previous discussion on the same topic here: https://github.com/itaysk/kubectl-neat/pull/58
So I do believe that kubectl-neat should remain simple and "just neat" BUT I'm open to ideas about anything we can do to improve it's "composability" or any aspect that will help make it more usable while preserving it's original scope.
