### ISSUE TITLE
Metadata isn't removed from lists

### ISSUE THREAD

**Issue by amirschw** [itaysk/kubectl-neat#68]
This part of code doesn't get executed when neat-ing lists:
https://github.com/itaysk/kubectl-neat/blob/f975c89fc129c8dd8013d19a7c2dd3f4a51a5dec/cmd/neat.go#L76-L88

Therefore, metadata isn't removed:
![image](https://user-images.githubusercontent.com/24677563/121200020-13e1d800-c87c-11eb-9cf9-e379c28e1151.png)

**Comment by itaysk** [comment]
@amirschw just to confirm, do you mean to say that the list-level metadata should be neated? as #82 did?

**Comment by amirschw** [comment]
@itaysk exactly!

**Comment by itaysk** [comment]
closed by https://github.com/itaysk/kubectl-neat/pull/82
