### ISSUE TITLE
Traefik IngressRoute tls option disappear 

### ISSUE THREAD

**Issue by den-vasyliev** [itaysk/kubectl-neat#69]
Be careful with next - spend 2 hours to found out on batch configuration. 

>k get ingressroute SomeRoute -o yaml
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match:PathPrefix(`/`)
    services:
    - name: service
      port: 8000
  tls: {}

>k get ingressroute SomeRoute -o yaml | kubectl neat
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match:PathPrefix(`/`)
    services:
    - name: service
      port: 8000

**Comment by itaysk** [comment]
thanks for reporting. probably the same issue as #18

**Comment by den-vasyliev** [comment]
can be rejected as dupple
