### ISSUE TITLE
Should this project version design under golang module semantic version?

### ISSUE THREAD

**Issue by alswl** [itaysk/kubectl-neat#72]
In golang library semantic version design, v2.x.x release is much difference of v1.x.x. All classes is not consistent. And if this library using go module, version 2 should using  in `github.com/itaysk/kubectl-neat/v2 v2.x.x` format.

My solution is fork this repo, and tag v2.0.3 as v1.20.0, so it works for me.

I wish this repo will migrate to `github.com/itaysk/kubectl-neat/v2` pkg structure, thanks.

**Comment by itaysk** [comment]
Hi @alswl thanks for the feedback. sounds reasonable to me, would you like to contribute this change?

**Comment by amitech** [comment]
@itaysk I am learning Go. It seems a newbie issue. Can I contribute to this?

**Comment by itaysk** [comment]
Yes feel free to work on any issue that isn't assigned
