### ISSUE TITLE
kubectl neat get all output to separate files

### ISSUE THREAD

**Issue by j4jes** [itaysk/kubectl-neat#79]
Hi, I'm currently using a script to dump everything in a namespace to yaml:

kubectl neat get all -n pos -o yaml > pos-all.yaml

I'm curious if there's an option similar to kompose tool to output yaml as separate files for each deployment, service, ingress ? I prefer having separate so I can organize them into folders. If this process were automated in a cron on a volume with snapshotting it would make for a great version control solution. Thanks!

**Comment by j4jes** [comment]
I put a bash script together to get all yaml out of a namespace, clean it with neat, and save into separate files. I didn't bother getting it to sort into folders yet which will be the next step, but I find this output much easier to work with:

```
#!/bin/bash
#dump all important yaml from current namespace

source ~/.bashrc
if ! type "kubectl-neat" > /dev/null; then
echo "kubegrab is missing some plugins, will attempt to install"
sleep 4
(
  set -x; cd "$(mktemp -d)" &&
  OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
  ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
  KREW="krew-${OS}_${ARCH}" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
  tar zxvf "${KREW}.tar.gz" &&
  ./"${KREW}" install krew
)
export PATH="$HOME/.krew/bin:$PATH"
echo 'export PATH="$HOME/.krew/bin:$PATH"' >> ~/.bashrc
kubectl krew install neat
echo ""
echo "Done installing needed plugins."
echo ""
fi

echo "kubectl neat present .."
echo ""
echo "currently using" $(kubectl config current-context)
echo ""
read -p "Do you want to grab relevant manifests in current namepace (y/n)" -n 1 -r
echo    # (optional) move to a new line
if [[ $REPLY =~ ^[Yy]$ ]]
then
for n in $(kubectl get -o=name pvc,configmap,ingress,service,secret,deployment,job,cronjob | grep -v 'secret/default-token')
#for n in $(kubectl get -o=name deployment | grep -v 'secret/default-token')
do
    kubectl neat get -o=yaml $n > $(basename $n)_$(dirname $n | cut -d. -f1).yaml
done

else
echo "exiting ..."
echo ""
exit
fi
```

**Comment by itaysk** [comment]
hi @j4jes , thanks for sharing your problem and solution. I think this is out of scope for kubectl-neat and should be solved in bash like you already did. Another way to consider (if you prefer the get all approach you started with) is to split the output into files. But yeah some bash glue will be required nonetheless
